name: deploy simple_bees

on:
  push:
    branches:
      - main
  schedule:
    - cron: '45 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Conda environment
        uses: actions/cache@v2
        with:
          path: ~/.conda
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: simple_bees
          environment-file: environment.yml

      - name: Activate Conda environment
        run: conda activate simple_bees

      - name: Run Python code
        run: |
          python main.py

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
